### ISSUE TITLE
Add missing required parameters to chronos batch system script

### ISSUE THREAD

**Issue by cmball1** [theferrit32/toil#7]
Missing and caused error when attempting to start a CWL workflow:

* `chronos.MissingFieldError: missing required field owner`
* `chronos.MissingFieldError: missing required field disabled`

Full traceback:
```
Traceback (most recent call last):
  File "/opt/toil/venv2.7/bin/cwltoil", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'cwltoil')()
  File "/opt/toil/src/toil/cwl/cwltoil.py", line 1048, in main
    outobj = toil.start(wf1)
  File "/opt/toil/src/toil/common.py", line 783, in start
    return self._runMainLoop(rootJobGraph)
  File "/opt/toil/src/toil/common.py", line 1057, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/opt/toil/src/toil/leader.py", line 212, in run
    self.innerLoop()
  File "/opt/toil/src/toil/leader.py", line 518, in innerLoop
    self._processReadyJobs()
  File "/opt/toil/src/toil/leader.py", line 444, in _processReadyJobs
    self._processReadyJob(jobGraph, resultStatus)
  File "/opt/toil/src/toil/leader.py", line 394, in _processReadyJob
    self.issueJob(JobNode.fromJobGraph(jobGraph))
  File "/opt/toil/src/toil/leader.py", line 590, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(jobNode)
  File "/opt/toil/src/toil/batchSystems/chronos.py", line 180, in issueBatchJob
    ret = client.add(job)
  File "/opt/toil/venv2.7/lib/python2.7/site-packages/chronos/__init__.py", line 127, in add
    self._check_fields(job_def)
  File "/opt/toil/venv2.7/lib/python2.7/site-packages/chronos/__init__.py", line 251, in _check_fields
    raise MissingFieldError("missing required field %s" % k)
```

**Comment by stevencox** [comment]
@theferrit32 - any thoughts on a cause?

**Comment by cmball1** [comment]
@stevencox from @theferrit32 `chronos python module apparently requires that even though the Chronos REST API does not`
